version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: social-app-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ./server
    container_name: social-app-backend
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./client
    container_name: social-app-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  mongo-data:
